// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxapprepositoryapi.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class ThrowRuntimeException extends CustomJavaAction<java.lang.Void>
{
	private java.lang.String message;

	public ThrowRuntimeException(IContext context, java.lang.String message)
	{
		super(context);
		this.message = message;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new RuntimeException(message);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ThrowRuntimeException";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
